name: hardhat test(yarn)

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.KROMA_GIT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Enable Corepack
        run: corepack enable && corepack prepare yarn@stable --activate

      - name: Cache Yarn dependencies
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn
        shell: bash

      - name: Caching solidity compiler
        uses: actions/cache@v3
        with:
          path: |
            ~/.solcx
            ~/.vvm
            ~/.brownie/packages
          key: ${{ runner.os }}-compiler-cache

      - name: Compile solidity
        run: yarn hardhat compile

      - name: Testing
        run: yarn hardhat test
